version: 2

updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: develop
    open-pull-requests-limit: 5
    groups:
      version-update:
        patterns:
          - '*'
